# Backpack Configuration File
#
# General
#   use-economy:
#       false - will not charge users to upgrade their backpacks.
#       true - users will be charges for backpack upgrades according to upgrade pricing below.
#   use-spout: Set to either true or false, this enables or disables hotkeys/additional guis support.
#   use-saveonlogin: saves the backpacks for each player once they login (fixes the dupe glitch but uses more resources)
#
# Admin
#   control-panel: Set to either true or false, this enables or disables the Control Panel Interface for Backpack for easy upgrading and other functions. use-spout *MUST* be enabled for this to work.
#   hotkey: Default value is set to KEY_V, this value can be changed to pre-set the hotkey to open the control panel. use-spout *MUST* be enabled for this to work.
#
# Backpack
#   hotkey: Default value is set to KEY_B, this value can be changed to pre-set the hotkey to open your backpack. use-spout *MUST* be enabled for this to work.
general:
  use-economy: false
  use-spoutplugin: true
  use-saveonlogin: false
admin:
  control-panel: false
  hotkey: KEY_V
backpack:
  default-size: 9
  maximum-no-perm-size: 9
  hotkey: KEY_B
  cost:
    slot18: 0
    slot27: 0
    slot36: 0
    slot45: 0
    slot54: 0