# Backpack Configuration File
#
# general:
#   use-economy:
#       false - will not charge users to upgrade their backpacks.
#       true - users will be charges for backpack upgrades according to upgrade pricing below.
#   use-spout:
#       true/false - Enables or disables hotkeys/additional guis support.
#   use-sql:
#       false - data storage will take place as flat PLAYERNAME.yml files.
#       true - data will be stored in sql database format.
#
# admin:
#   control-panel:
#       true/false - Enables or disables the Control Panel Interface for Backpack for easy upgrading and other functions. use-spout *MUST* be enabled for this to work.
#   hotkey:
#       Default Value - KEY_V, this value can be changed to pre-set the hotkey to open the control panel. use-spout *MUST* be enabled for this to work.
#
# backpack:
#   hotkey:
#       Default Value - KEY_B, this value can be changed to pre-set the hotkey to open your backpack. use-spout *MUST* be enabled for this to work.
#
# storage:
#   host:
#       Typically this is localhost.
#   port:
#       default port for mysql is 3306.
#   database:
#       database or schema name.
#   username:
#       username with sufficient privileges to access and make changes to db.
#   password:
#       password for above username.
#
general:
  use-economy: false
  use-spout: false
  use-sql: false
admin:
  control-panel: false
  hotkey: KEY_V
backpack:
  no-perm-default-size: 9
  hotkey: KEY_B
storage:
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: password