name: Backpack
version: dev-SNAPSHOT
description: Backpack is a plugin for Spout that gives users a handy backpack for inventory.

author: Zidane
authors: [Zidane, Dockter]

main: com.almuramc.backpack.bukkit.BackpackPlugin
softdepend: [Spout]
load: POSTWORLD
