name: ${project.name}
version: ${buildNumber}
description: ${project.description}
author: ${project.organization.name}
website: ${project.organization.url}

main: com.almuramc.backpack.bukkit.BackpackPlugin
softdepend: [Spout, Vault]
load: POSTWORLD

commands:
    backpack:
        description: Manage Backpacks
        usage: /backpack [command] [arguments]
permissions:
    backpack.admin:
        description: Gives you access to /backpack clear player
        default: op
    backpack.use:
        description: Allows users to access backpack.
        default: true
    backpack.keepitems:
        description: Allows users to keep backpack items on death.
        default: op
    backpack.upgrade:
        description: Allows users to upgrade their backpacks beyond 9 slots.
        default: op
    backpack.workbench:
        description: Allows users to use workbench if it exists in the users backpack or inventory.
        default: op